# Generated by Django 5.0.1 on 2024-03-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.IntegerField(
                default="1902080487",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(
                default="3020105805",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
