# Generated by Django 5.0.3 on 2024-04-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_affiliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('activation_key', models.UUIDField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
