# Generated by Django 5.0.4 on 2024-04-06 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_activation"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
