# Generated by Django 5.0.1 on 2024-01-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_posts_delete_fileupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user_id',
            new_name='user',
        ),
    ]
