# Generated by Django 5.0 on 2024-04-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_activation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('need_changes', 'Changes_Reqd'), ('reviewed', 'Reviewed')], default='Ongoing', max_length=20),
        ),
    ]
