# Generated by Django 5.0.4 on 2024-05-30 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Need_changes', 'Need_changes'), ('Reviewed', 'Reviewed')], default='Ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='pdf_file_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Need_changes', 'Need_changes'), ('Reviewed', 'Reviewed')], default='Ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('editor', 'Editor'), ('normal_user', 'Normal_User'), ('reviewer', 'Manuscript_Reviewer'), ('developer', 'Web_developer')], default='normal_user', max_length=20, null=True),
        ),
    ]
