# Generated by Django 5.0.1 on 2024-01-24 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
