# Generated by Django 5.0 on 2024-01-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_posts_document_alter_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='document',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
