# Generated by Django 5.0.4 on 2024-06-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_post_status_alter_review_pdf_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='for_user',
            field=models.BooleanField(default=False),
        ),
    ]
