# Generated by Django 5.0.4 on 2024-07-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_review_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
