# Generated by Django 5.0.1 on 2024-03-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_post_id_alter_user_id_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                default="5252099673", editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default="1105118953", editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
