# Generated by Django 5.0.4 on 2024-07-07 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_new_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
