# Generated by Django 5.0.1 on 2024-03-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_post_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                default="2604629643", editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default="9775474705", editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
