# Generated by Django 5.0.1 on 2024-03-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_post_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.IntegerField(
                default="5174704666",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(
                default="2381646243",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
