# Generated by Django 5.0.1 on 2024-03-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_categories_institute_user_area_of_research_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="affilation",
            new_name="affiliation",
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.IntegerField(
                default="2687179833",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(
                default="1377492294",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
