# Generated by Django 5.0.1 on 2024-03-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_rename_affilation_user_affiliation_alter_post_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.IntegerField(
                default="2781134735",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(
                default="2168833007",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
