# Generated by Django 5.0.1 on 2024-03-06 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_alter_post_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.IntegerField(
                default="2132464540",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="affiliation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.institute",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(
                default="1648059861",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
