# Generated by Django 5.0.1 on 2024-03-06 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_alter_post_id_alter_user_affiliation_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="name",
            field=models.CharField(
                choices=[
                    ("robotics", "Robotics"),
                    ("manufacturing", "Manufacturing"),
                    ("drone", "Drone"),
                    ("manipulator", "Manipulator"),
                    ("humanoids", "Humanoids"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.categories",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.IntegerField(
                default="2529888425",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(
                default="1614044528",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
