# Generated by Django 5.0.1 on 2024-03-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_categories_name_user_default_category_alter_post_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.IntegerField(
                default="9521234752",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(
                default="1297564580",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
