# Generated by Django 5.0.1 on 2024-03-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_alter_post_id_alter_user_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categories",
            new_name="Category",
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.IntegerField(
                default="1035662282",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(
                default="1153160316",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
