export const NEWS_GET_ALL_REQUEST = "NEWS_GET_ALL_REQUEST";
export const NEWS_GET_ALL_REQUEST_SUCCESS = "NEWS_GET_ALL_REQUEST_SUCCESS";
export const NEWS_GET_ALL_REQUEST_FAIL = "NEWS_GET_ALL_REQUEST_FAIL";
export const NEWS_GET_ALL_REQUEST_RESET = "NEWS_GET_ALL_REQUEST_RESET";
