export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";

export const POST_UPLOAD_REQUEST = "POST_UPLOAD_REQUEST";
export const POST_UPLOAD_SUCCESS = "POST_UPLOAD_SUCCESS";
export const POST_UPLOAD_FAIL = "POST_UPLOAD_FAIL";

export const USER_POSTS_REQUEST = "USER_POSTS_REQUEST";
export const USER_POSTS_SUCCESS = "USER_POSTS_SUCCESS";
export const USER_POSTS_FAIL = "USER_POSTS_FAIL";

export const CATEGORIES_GET_ALL_REQUEST = "CATEGORIES_GET_ALL_REQUEST";
export const CATEGORIES_GET_ALL_REQUEST_SUCCESS =
  "CATEGORIES_GET_ALL_REQUEST_SUCCESS";
export const CATEGORIES_GET_ALL_REQUEST_FAIL =
  "CATEGORIES_GET_ALL_REQUEST_FAIL";
export const CATEGORIES_GET_ALL_REQUEST_RESET =
  "CATEGORIES_GET_ALL_REQUEST_RESET";

export const POST_ASSIGNED_REQUEST = "POST_ASSIGNED_REQUEST";
export const POST_ASSIGNED_REQUEST_SUCCESS = "POST_ASSIGNED_REQUEST";
export const POST_ASSIGNED_REQUEST_FAILURE = "POST_ASSIGNED_REQUEST";


export const SUBCAT_GET_ALL_REQUEST = "CATEGORIES_GET_ALL_REQUEST";
export const SUBCAT_GET_ALL_SUCCESS ="SUBCAT_GET_ALL_SUCCESS";
export const SUBCAT_GET_ALL_FAIL ="SUBCAT_GET_ALL_FAIL";
export const SUBCAT_GET_ALL_RESET ="SUBCAT_GET_ALL_RESET";


export const POST_UNASSIGNED_REQUEST = "POST_UNASSIGNED_REQUEST";
export const POST_UNASSIGNED_REQUEST_SUCCESS = "POST_UNASSIGNED_REQUEST";
export const POST_UNASSIGNED_REQUEST_FAILURE = "POST_UNASSIGNED_REQUEST";



export const UNDER_PROCEES_POST_LIST_REQUEST='UNDER_PROCEES_POST_LIST_REQUEST';
export const UNDER_PROCEES_POST_LIST_SUCCESS='UNDER_PROCEES_POST_LIST_SUCCESS';
export const UNDER_PROCEES_POST_LIST_FAIL='UNDER_PROCEES_POST_LIST_FAIL';
export const UNDER_PROCEES_POST_LIST_RESET='UNDER_PROCEES_POST_LIST_RESET';