export const REVIEW_ASSIGN_REQUEST = "REVIEW_ASSIGN_REQUEST";
export const REVIEW_ASSIGN_SUCCESS = "REVIEW_ASSIGN_SUCCESS";
export const REVIEW_ASSIGN_FAIL = "REVIEW_ASSIGN_FAIL";
export const REVIEW_ASSIGN_RESET = "REVIEW_ASSIGN_RESET";


