export const REVIEW_ASSIGN_REQUEST = "REVIEW_ASSIGN_REQUEST";
export const REVIEW_ASSIGN_SUCCESS = "REVIEW_ASSIGN_SUCCESS";
export const REVIEW_ASSIGN_FAIL = "REVIEW_ASSIGN_FAIL";
export const REVIEW_ASSIGN_RESET = "REVIEW_ASSIGN_RESET";


export const EDITOR_REVIEWS_REQUEST = "EDITOR_REVIEWS_REQUEST";
export const EDITOR_REVIEWS_SUCCESS = "EDITOR_REVIEWS_SUCCESS";
export const EDITOR_REVIEWS_FAIL = "EDITOR_REVIEWS_FAIL";
export const EDITOR_REVIEWS_RESET = "EDITOR_REVIEWS_RESET";