export const REVIEW_ASSIGN_REQUEST = "REVIEW_ASSIGN_REQUEST";
export const REVIEW_ASSIGN_SUCCESS = "REVIEW_ASSIGN_SUCCESS";
export const REVIEW_ASSIGN_FAIL = "REVIEW_ASSIGN_FAIL";
export const REVIEW_ASSIGN_RESET = "REVIEW_ASSIGN_RESET";


export const EDITOR_REVIEWS_REQUEST = "EDITOR_REVIEWS_REQUEST";
export const EDITOR_REVIEWS_SUCCESS = "EDITOR_REVIEWS_SUCCESS";
export const EDITOR_REVIEWS_FAIL = "EDITOR_REVIEWS_FAIL";
export const EDITOR_REVIEWS_RESET = "EDITOR_REVIEWS_RESET";



export const EDIT_REVIEW_REQUEST="EDIT_REVIEW_REQUEST"
export const EDIT_REVIEW_SUCCESS="EDIT_REVIEW_SUCCESS"
export const EDIT_REVIEW_FAIL="EDIT_REVIEW_FAIL"
export const EDIT_REVIEW_RESET="EDIT_REVIEW_RESET"



export const REVIEWS_REVIEWED_REQUEST = "REVIEWS_REVIEWED_REQUEST";
export const REVIEWS_REVIEWED_SUCCESS = "REVIEWS_REVIEWED_SUCCESS";
export const REVIEWS_REVIEWED_FAILURE = "EVIEWS_REVIEWED_FAILURE";