export const USER_VERIFY_REQUEST = "USER_VERIFY_REQUEST";
export const USER_VERIFY_EMAIL = "USER_VERIFY_EMAIL";
export const USER_VERIFY_SUCCESS = "USER_VERIFY_SUCCESS";
export const USER_VERIFY_FAIL = "USER_VERIFY_FAIL";
export const USER_VERIFY_RESET = "USER_VERIFY_RESET";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";
export const USER_PROFILE_RESET = "USER_PROFILE_RESET";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const UPDATE_AUTH_TOKEN='UPDATE_AUTH_TOKEN'

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USERS_GET_ALL_REQUEST = "USERS_GET_ALL_REQUEST";
export const USERS_GET_ALL_REQUEST_SUCCESS = "USER_GET_ALL_REQUEST_SUCCESS";
export const USERS_GET_ALL_REQUEST_FAIL = "USER_GET_ALL_REQUEST_FAIL";
export const USERS_GET_ALL_REQUEST_RESET = "USER_GET_ALL_REQUEST_RESET";


export const TOKEN_REFRESH_REQUEST='TOKEN_REFRESH_REQUEST'
export const TOKEN_REFRESH_SUCCESS='TOKEN_REFRESH_SUCCESS'
export const TOKEN_REFRESH_FAIL='TOKEN_REFRESH_FAIL'



export const EDITORS_GET_ALL_REQUEST='EDITOR_GET_ALL_REQUEST'
export const EDITORS_GET_ALL_SUCCESS='EDITOR_GET_ALL_SUCCESS'
export const EDITORS_GET_ALL_FAIL='EDITOR_GET_ALL_FAIL'
export const EDITORS_GET_ALL_RESET='EDITOR_GET_ALL_RESET'




  